export default [
  "M2Love",
  "I adore you",
  "I’m affectionate for you",
  "I’m attached to you",
  "I’m enchanted by you",
  "You’re my missing piece",
  "You’re the only one for me",
  "I’m totally devoted to you",
  "I’m infatuated with you",
  "I’m mad about you",
  "You’re all I see",
  "I’m passionate about you",
  "I’m enraptured with you",
  "I relish you",
  "You’re the light of my life",
  "You’re my soft spot",
  "I’m tender for you",
  "I’m wild about you",
  "I worship you",
  "You’re my everything",
  "I admire you so much",
  "I adulate you",
  "I more than care for you",
  "I cherish you like nothing else",
  "I delight in your company",
  "No one matters but you",
  "I dote on you",
  "I’m falling for you",
  "I fancy you",
  "I only have eyes for you",
  "You’re my hero",
  "I’ve flipped over you",
  "You make me feel young",
  "You’re on my mind",
  "You’re wonderful to me",
  "You’re adorable to me",
  "You amaze me",
  "You blow me away",
  "You electrify me",
  "My feelings are overwhelmed by you",
  "You make my life worth living",
  "You’re my inspiration",
  "You make me feel good about myself",
  "I’m stupefied by you",
  "I idolize you",
  "I long for you",
  "You’re my treasure",
  "I delight in you",
  "I glorify you",
  "I laud you",
  "I dig you",
  "I totally go for you",
  "You’re just my style",
  "You’re my prize",
  "I hold you in reverence",
  "I venerate you",
  "You comfort me",
  "You nourish me",
  "I enshrine you",
  "I hold you dear",
  "I honor you",
  "You nurture me",
  "You sustain me",
  "I want you so badly",
  "I’m crazy about you",
  "I’m nuts about you",
  "You’re my one and only",
  "You’re everything to me",
  "You complete me",
  "You make me whole",
  "I luxuriate in you",
  "I need you more than anything",
  "You’re special to me",
  "You make me whole",
  "I’m nothing without you",
  "You’re the air I breath",
  "I’ve looked for you my entire life",
  "I miss you so much",
  "I would be lost without you",
  "You’re my savior",
  "You’re my stars and moon",
  "I’m bedazzled by you",
  "You’re my aphrodisiac",
  "I’m sweet on you",
  "I glory in you",
  "I savor every moment with you",
  "I’m infatuated with you",
  "I’m beguiled with you",
  "I’m besotted by you",
  "You carry me away",
  "I’m charmed by you",
  "I’m hooked on you",
  "I’m intoxicated by you",
  "You’re my indulgence",
  "You’re my obsession",
  "You’re my enchantment",
  "I burn for you",
  "You fill my heart",
  "I’m fond of you"
];
